# Generated by Django 5.1 on 2024-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rename_ip_device_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['serial_number']},
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.PositiveIntegerField(),
        ),
    ]
