# Generated by Django 5.1 on 2024-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_device_options_alter_device_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Up', 'Up'), ('Down', 'Down')], editable=False, max_length=10),
        ),
    ]
