# Generated by Django 5.1 on 2025-04-10 05:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_device_bandwidth_device_cpu_usage_device_latency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'verbose_name_plural': 'Notification Preferences'},
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='frequency',
        ),
        migrations.AddField(
            model_name='device',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='device',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notification_times',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='snmp_version',
            field=models.CharField(choices=[('1', 'v1'), ('2c', 'v2c'), ('3', 'v3')], default='2c', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('Up', 'Up'), ('Down', 'Down'), ('Unknown', 'Unknown')], default='Down', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='interval',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='DeviceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('latency', models.FloatField(blank=True, null=True)),
                ('bandwidth', models.FloatField(blank=True, null=True)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('alert_message', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='network.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='network_dev_timesta_a0dc2a_idx'), models.Index(fields=['device', 'timestamp'], name='network_dev_device__5ae78d_idx')],
            },
        ),
    ]
